local colors = require("base16").get_theme_tb("base_30")

return {
  -- Bufferline
  BufferLineBackground = { fg = colors.light_grey, bg = colors.black2 },
  BufferlineIndicatorVisible = { fg = colors.black2, bg = colors.black2 },
  BufferLineBufferSelected = { fg = colors.white, bg = colors.black },
  BufferLineBufferVisible = { fg = colors.light_grey, bg = colors.black2 },
  BufferLineError = { fg = colors.light_grey, bg = colors.black2 },
  BufferLineErrorDiagnostic = { fg = colors.light_grey, bg = colors.black2 },
  BufferLineCloseButton = { fg = colors.light_grey, bg = colors.black2 },
  BufferLineCloseButtonVisible = { fg = colors.light_grey, bg = colors.black2 },
  BufferLineCloseButtonSelected = { fg = colors.red, bg = colors.black },
  BufferLineFill = { fg = colors.grey_fg, bg = colors.black2 },
  BufferlineIndicatorSelected = { fg = colors.black, bg = colors.black },
  BufferLineModified = { fg = colors.red, bg = colors.black2 },
  BufferLineModifiedVisible = { fg = colors.red, bg = colors.black2 },
  BufferLineModifiedSelected = { fg = colors.green, bg = colors.black },
  BufferLineSeparator = { fg = colors.black2, bg = colors.black2 },
  BufferLineSeparatorVisible = { fg = colors.black2, bg = colors.black2 },
  BufferLineSeparatorSelected = { fg = colors.black2, bg = colors.black2 },
  BufferLineTab = { fg = colors.light_grey, bg = colors.one_bg3 },
  BufferLineTabSelected = { fg = colors.black2, bg = colors.nord_blue },
  BufferLineTabClose = { fg = colors.red, bg = colors.black },
  BufferLineDevIconDefaultSelected = { bg = "none" },
  BufferLineDevIconDefaultInactive = { bg = "none" },
  BufferLineDuplicate = { fg = "NONE", bg = colors.black2 },
  BufferLineDuplicateSelected = { fg = colors.red, bg = colors.black },
  BufferLineDuplicateVisible = { fg = colors.blue, bg = colors.black2 },
  BufferLineRightCustomAreaText1 = { fg = colors.white },
  BufferLineRightCustomAreaText2 = { fg = colors.red },

  -- builtIn
  lineFill = { bg = colors.black2 },
  LineBufOn = { fg = colors.white, bg = colors.black },
  LineBufOff = { fg = colors.light_grey, bg = colors.black2 },
  LineBufOnModified = { fg = colors.green, bg = colors.black },
  BufLineBufOffModified = { fg = colors.red, bg = colors.black2 },
  LineBufOnClose = { fg = colors.red, bg = colors.black },
  LineBufOffClose = { fg = colors.light_grey, bg = colors.black2 },
  lineTabNewBtn = { fg = colors.white, bg = colors.one_bg3 },
  LineTabOn = { fg = colors.black, bg = colors.nord_blue },
  LineTabOff = { fg = colors.white, bg = colors.one_bg2 },
  LineTabCloseBtn = { fg = colors.black, bg = colors.nord_blue },
  TabTitle = { fg = colors.black, bg = colors.white },
  LineThemeToggleBtn = { fg = colors.white, bg = colors.one_bg3 },
  LineCloseAllBufsBtn = { bg = colors.red, fg = colors.black },
}
