local theme = require("base16").get_theme_tb("base_30")

return {
  TSComment = { fg = theme.grey },
  TSAnnotation = { fg = theme.blue },
  TSAttribute = { fg = theme.cyan },
  TSConstructor = { fg = theme.yellow },
  TSType = { fg = theme.yellow },
  TSTypeBuiltin = { fg = theme.yellow },
  TSConditional = { fg = theme.purple },
  TSException = { fg = theme.purple },
  TSInclude = { fg = theme.purple },
  TSKeyword = { fg = theme.purple },
  TSKeywordReturn = { fg = theme.purple },
  TSKeywordFunction = { fg = theme.purple },
  TSLabel = { fg = theme.blue },
  TSNone = { fg = theme.fg },
  TSNamespace = { fg = theme.purple },
  TSRepeat = { fg = theme.purple },
  TSConstant = { fg = theme.orange },
  TSConstBuiltin = { fg = theme.orange },
  TSFloat = { fg = theme.orange },
  TSNumber = { fg = theme.orange },
  TSBoolean = { fg = theme.orange },
  TSCharacter = { fg = theme.green },
  TSError = { fg = theme.error_red },
  TSFunction = { fg = theme.blue },
  TSFuncBuiltin = { fg = theme.blue },
  TSMethod = { fg = theme.blue },
  TSConstMacro = { fg = theme.cyan },
  TSFuncMacro = { fg = theme.blue },
  TSProperty = { fg = theme.cyan },
  TSOperator = { fg = theme.purple },
  TSField = { fg = theme.blue },
  TSParameter = { fg = theme.red },
  TSParameterReference = { fg = theme.red },
  TSVariable = { fg = theme.fg },
  TSVariableBuiltin = { fg = theme.red },
  TSSymbol = { fg = theme.cyan },
  TSText = { fg = theme.fg },
  TSTextReference = { fg = theme.red },
  TSPunctDelimiter = { fg = theme.fg },
  TSTagDelimiter = { fg = theme.grey },
  TSTagAttribute = { fg = theme.orange },
  TSPunctBracket = { fg = theme.fg },
  TSPunctSpecial = { fg = theme.fg },
  TSString = { fg = theme.green },
  TSStringRegex = { fg = theme.orange },
  TSStringEscape = { fg = theme.orange },
  TSTag = { fg = theme.blue },
  -- TSEmphasis = { style = "italic" },
  -- TSUnderline = { style = "underline" },
  -- TSNote = { fg = theme.info_yellow, style = "bold" },
  -- TSWarning = { fg = theme.warning_orange, style = "bold" },
  -- TSDanger = { fg = theme.error_red, style = "bold" },
  TSTitle = { fg = theme.blue },
  TSLiteral = { fg = theme.green },
  TSURI = { fg = theme.blue },
  TSMath = { fg = theme.fg },
  TSKeywordOperator = { fg = theme.purple },
  TSStructure = { fg = theme.fg },
  -- TSStrong = { fg = theme.yellow_orange },
  -- TSQueryLinterError = { fg = theme.warning_orange },
  TSEnvironment = { fg = theme.fg },
  TSEnvironmentName = { fg = theme.fg },
}
