local colors = require("ui").get()
local fg = require("ui").fg
local bg = require("ui").bg
local fg_bg = require("ui").fg_bg

-- BufferLine
fg_bg("BufferLineBackground", colors.light_grey, colors.black2)
fg_bg("BufferLineBufferSelected", colors.white, colors.black)
fg_bg("BufferLineBufferVisible", colors.light_grey, colors.black2)
fg_bg("BufferLineError", colors.light_grey, colors.black2)
fg_bg("BufferLineErrorDiagnostic", colors.light_grey, colors.black2)
fg_bg("BufferLineCloseButton", colors.light_grey, colors.black2)
fg_bg("BufferLineCloseButtonVisible", colors.light_grey, colors.black2)
fg_bg("BufferLineCloseButtonSelected", colors.red, colors.black)
fg_bg("BufferLineFill", colors.grey_fg, colors.black2)
fg_bg("BufferlineIndicatorSelected", colors.blue, colors.black)
fg_bg("BufferLineModified", colors.red, colors.black2)
fg_bg("BufferLineModifiedVisible", colors.red, colors.black2)
fg_bg("BufferLineModifiedSelected", colors.green, colors.black)
fg_bg("BufferLineSeparator", colors.black2, colors.black2)
fg_bg("BufferLineSeparatorVisible", colors.black2, colors.black2)
fg_bg("BufferLineSeparatorSelected", colors.black2, colors.black2)
fg_bg("BufferLineTab", colors.light_grey, colors.one_bg3)
fg_bg("BufferLineTabSelected", colors.black2, colors.nord_blue)
fg_bg("BufferLineTabClose", colors.red, colors.black)
bg("BufferLineDevIconDefaultSelected", "none")
bg("BufferLineDevIconDefaultInactive", "none")
fg_bg("BufferLineDuplicate", "NONE", colors.black2)
fg_bg("BufferLineDuplicateSelected", colors.red, colors.black)
fg_bg("BufferLineDuplicateVisible", colors.blue, colors.black2)
fg("BufferLineRightCustomAreaText1", colors.white)
fg("BufferLineRightCustomAreaText2", colors.red)

-- BuiltIn
bg("lineFill", colors.black2)
fg_bg("LineBufOn", colors.white, colors.black)
fg_bg("LineBufOff", colors.light_grey, colors.black2)
fg_bg("LineBufOnModified", colors.green, colors.black)
fg_bg("BufLineBufOffModified", colors.red, colors.black2)
fg_bg("LineBufOnClose", colors.red, colors.black)
fg_bg("lineTabNewBtn", colors.white, colors.one_bg3)
fg_bg("LineTabOn", colors.black, colors.nord_blue)
fg_bg("LineTabOff", colors.white, colors.black2)
fg_bg("LineTabCloseBtn", colors.black, colors.nord_blue)
fg_bg("TabTitle", colors.black, colors.white)
fg_bg("LineCloseAllBufsBtn", colors.black, colors.red)
fg_bg("LineBufOffClose", colors.light_grey, colors.black2)
fg_bg("LineThemeToggleBtn", colors.white, colors.black)
