local colors = require("ui").base16_get()
local fg = require("ui").fg
local fg_bg = require("ui").fg_bg

fg("CmpItemAbbr", colors.white)
fg("CmpItemAbbrMatch", colors.blue)
fg("CmpBorder", colors.grey)
fg_bg("CmpDocBorder", colors.darker_black, colors.darker_black)
fg("CmPmenu", colors.darker_black)
fg("CmpItemKindSnippet", colors.red)
fg("CmpItemKindConstructor", colors.blue)
fg("CmpItemKindColor", colors.red)
fg("CmpItemKindConstant", colors.orange)
fg("CmpItemKindIdentifier", colors.red)
fg("CmpItemKindField", colors.red)
fg("CmpItemKindProperty", colors.red)
fg("CmpItemKindTypeParameter", colors.red)
fg("CmpItemKindFunction", colors.folder_bg)
fg("CmpItemKindMethod", colors.folder_bg)
fg("CmpItemKindVariable", colors.dark_purple)
fg("CmpItemKindStructure", colors.purple)
fg("CmpItemKindUnit", colors.purple)
fg("CmpItemKindStruct", colors.purple)
fg("CmpItemKindText", colors.green)
fg("CmpItemKindType", colors.yellow)
fg("CmpItemKindModule", colors.purple)
fg("CmpItemKindKeyword", colors.white)
fg("CmpItemKindFolder", colors.green)
fg("CmpItemKindFile", colors.green)
fg("CmpItemKindReference", colors.white)
fg("CmpItemKindOperator", colors.dark_purple)
