local colors = require("base16").get()
local fg = require("base16").fg

fg("DevIconDefault", colors.red)
fg("DevIconc", colors.blue)
fg("DevIconcss", colors.blue)
fg("DevIcondeb", colors.cyan)
fg("DevIconDockerfile", colors.cyan)
fg("DevIconhtml", colors.baby_pink)
fg("DevIconjpeg", colors.dark_purple)
fg("DevIconjpg", colors.dark_purple)
fg("DevIconjs", colors.sun)
fg("DevIconkt", colors.orange)
fg("DevIconlock", colors.red)
fg("DevIconlua", colors.blue)
fg("DevIconmp3", colors.white)
fg("DevIconmp4", colors.white)
fg("DevIconout", colors.white)
fg("DevIconpng", colors.dark_purple)
fg("DevIconpy", colors.cyan)
fg("DevIcontoml", colors.blue)
fg("DevIconts", colors.teal)
fg("DevIconttf", colors.white)
fg("DevIconrb", colors.pink)
fg("DevIconrpm", colors.orange)
fg("DevIconvue", colors.vibrant_green)
fg("DevIconwoff", colors.white)
fg("DevIconwoff2", colors.white)
fg("DevIconxz", colors.sun)
fg("DevIconzip", colors.sun)
fg("DevIconZig", colors.orange)
